"""Generic fallback pack.

Used when no domain-specific pack claims the requirement. It still produces a
coherent, testable scaffold (a service module, a passing test, and docs) so the
pipeline always yields reviewable artifacts instead of failing on unknown input.
"""

from __future__ import annotations

from agentic_sdlc.knowledge.base import KnowledgePack
from agentic_sdlc.models import AnalysisResult, ApiEndpoint, Architecture, Artifact

_INIT = '''"""Generated service scaffold."""

from .core import Service

__all__ = ["Service"]
'''

_CORE = '''"""Core service scaffold generated from the normalized requirement.

Replace the placeholder logic in :meth:`Service.handle` with the real
implementation. The surrounding structure — validation, a typed result, and a
seam for persistence — is already in place.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


class ValidationError(ValueError):
    """Raised when an inbound request fails validation."""


@dataclass
class Result:
    ok: bool
    data: Any = None
    error: str = ""


class Service:
    """Thin, testable core. The API/CLI layer should adapt onto this class."""

    def __init__(self, store: dict | None = None) -> None:
        self._store: dict = store if store is not None else {}

    def handle(self, request: dict) -> Result:
        if not isinstance(request, dict):
            raise ValidationError("request must be a mapping")
        key = request.get("key")
        if not key:
            raise ValidationError("request.key is required")
        self._store[key] = request.get("value")
        return Result(ok=True, data={"key": key})

    def get(self, key: str) -> Result:
        if key not in self._store:
            return Result(ok=False, error="not found")
        return Result(ok=True, data=self._store[key])
'''

_TEST_CORE = '''"""Unit tests for the generated service scaffold."""

import unittest

from app.core import Service, ValidationError


class ServiceTests(unittest.TestCase):
    def setUp(self):
        self.svc = Service()

    def test_handle_stores_value(self):
        result = self.svc.handle({"key": "a", "value": 1})
        self.assertTrue(result.ok)
        self.assertEqual(self.svc.get("a").data, 1)

    def test_missing_key_rejected(self):
        with self.assertRaises(ValidationError):
            self.svc.handle({"value": 1})

    def test_get_unknown_returns_not_ok(self):
        self.assertFalse(self.svc.get("missing").ok)


if __name__ == "__main__":
    unittest.main()
'''

_README = '''# Generated Service

A scaffold generated by the Agentic SDLC system from the supplied requirement.

## Test

```bash
python -m unittest discover -s tests -v
```

## Next steps

Implement the real behaviour inside `app/core.py::Service.handle` and grow the
test suite alongside it.
'''

_ARCH = '''# Architecture

- **`app/core.py`** — framework-agnostic `Service` with validation and a storage seam.
- **`tests/`** — unittest suite that runs with the standard library only.

Adapt an API or CLI layer onto `Service` without changing the core logic.
'''


class GenericPack(KnowledgePack):
    """Catch-all pack for requirements without a dedicated domain generator."""

    domain = "generic"

    @classmethod
    def matches(cls, text: str) -> bool:
        # The generic pack is the explicit fallback; the provider only reaches it
        # when nothing else matched, so it always accepts.
        return True

    def architecture(self, analysis: AnalysisResult) -> Architecture:
        return Architecture(
            overview=(
                "A layered scaffold: a framework-agnostic service core with a "
                "storage seam, wrapped by an adaptable API/CLI layer."
            ),
            components=[
                "Service core — validation and business logic",
                "Storage seam — in-memory map, replaceable with a real datastore",
                "Adapter layer — API/CLI wrapper (to be implemented)",
            ],
            data_model=["key/value store placeholder — replace with the real schema"],
            api=[
                ApiEndpoint("POST", "/handle", "Handle a request",
                            request="{key, value}", response="{ok, data}", status=200),
            ],
            decisions=[
                "Separate a testable core from transport so logic is unit-testable.",
                "Keep persistence behind a seam to defer the datastore decision.",
            ],
            tradeoffs=[
                "A generic scaffold trades domain specificity for broad applicability; "
                "the core must be filled in for the concrete problem.",
            ],
        )

    def code(self, analysis: AnalysisResult, architecture: Architecture) -> list[Artifact]:
        return [
            Artifact("app/__init__.py", _INIT, "code"),
            Artifact("app/core.py", _CORE, "code"),
        ]

    def tests(
        self,
        analysis: AnalysisResult,
        architecture: Architecture,
        code: list[Artifact],
    ) -> list[Artifact]:
        return [Artifact("tests/test_core.py", _TEST_CORE, "test")]

    def docs(self, analysis: AnalysisResult, architecture: Architecture) -> list[Artifact]:
        return [
            Artifact("README.md", _README, "docs"),
            Artifact("docs/ARCHITECTURE.md", _ARCH, "docs"),
        ]
