"""Core business logic for URL shortening: creation, resolution, update, delete, stats, bulk.

Short codes are generated by base62-encoding an auto-incrementing SQLite row
id (standing in for a distributed Snowflake-like generator), which guarantees
uniqueness without a collision-retry loop.
"""
import threading
from datetime import datetime, timezone

from .validation import validate_url, validate_alias, ValidationError
from .storage import TTLCache
from .analytics import ClickEvent

ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"


def base62_encode(n):
    if n == 0:
        return ALPHABET[0]
    digits = []
    while n:
        n, rem = divmod(n, 62)
        digits.append(ALPHABET[rem])
    return "".join(reversed(digits))


class ConflictError(Exception):
    """Raised when a requested custom alias is already taken."""


class PermissionDeniedError(Exception):
    """Raised when a caller attempts to modify a URL they do not own."""


class NotFoundError(Exception):
    """Raised when a short code does not exist."""


def now_iso():
    return datetime.now(timezone.utc).isoformat()


class URLShortenerService:
    """Coordinates storage, validation, caching and analytics for URL shortening."""

    def __init__(self, db, analytics_queue, base_url="http://localhost:8080"):
        self.db = db
        self.queue = analytics_queue
        self.base_url = base_url.rstrip("/")
        self.cache = TTLCache(maxsize=20000, ttl=60)
        self._lock = threading.Lock()

    def _generate_unique_code(self):
        """Atomically reserve a new row and derive its base62 short code from the row id."""
        with self._lock:
            cur = self.db.execute(
                "INSERT INTO urls (short_code, long_url, created_at) VALUES (?, ?, ?)",
                ("__pending__", "", now_iso()),
            )
            new_id = cur.lastrowid
            code = base62_encode(new_id)
            self.db.execute("UPDATE urls SET short_code = ? WHERE id = ?", (code, new_id))
            return code, new_id

    def create_url(self, long_url, custom_alias=None, expires_at=None, owner_key=None):
        validate_url(long_url)
        validate_alias(custom_alias)
        created = now_iso()
        if custom_alias:
            existing = self.db.query_one("SELECT 1 FROM urls WHERE short_code = ?", (custom_alias,))
            if existing:
                raise ConflictError("alias already in use")
            self.db.execute(
                "INSERT INTO urls (short_code, long_url, owner_key, custom_alias, created_at, expires_at, active) "
                "VALUES (?, ?, ?, 1, ?, ?, 1)",
                (custom_alias, long_url, owner_key, created, expires_at),
            )
            code = custom_alias
        else:
            code, new_id = self._generate_unique_code()
            self.db.execute(
                "UPDATE urls SET long_url = ?, owner_key = ?, created_at = ?, expires_at = ?, active = 1 "
                "WHERE id = ?",
                (long_url, owner_key, created, expires_at, new_id),
            )
        return {
            "short_code": code,
            "short_url": f"{self.base_url}/{code}",
            "long_url": long_url,
            "expires_at": expires_at,
            "created_at": created,
        }

    def create_bulk(self, urls, owner_key=None):
        results = []
        for item in urls:
            long_url = item.get("long_url") if isinstance(item, dict) else item
            alias = item.get("custom_alias") if isinstance(item, dict) else None
            expires_at = item.get("expires_at") if isinstance(item, dict) else None
            try:
                res = self.create_url(long_url, custom_alias=alias, expires_at=expires_at, owner_key=owner_key)
                results.append({"long_url": long_url, "short_code": res["short_code"], "error": None})
            except (ValidationError, ConflictError) as exc:
                results.append({"long_url": long_url, "short_code": None, "error": str(exc)})
        return results

    def resolve(self, short_code, referrer=None, user_agent=None, ip=None):
        """Resolve a short code to its long URL, recording a click event (non-blocking)."""
        long_url = self.cache.get(short_code)
        if long_url is None:
            row = self.db.query_one(
                "SELECT long_url, active, expires_at FROM urls WHERE short_code = ?", (short_code,)
            )
            if row is None or not row["active"]:
                return None
            if row["expires_at"] and row["expires_at"] < now_iso():
                return None
            long_url = row["long_url"]
            self.cache.set(short_code, long_url)
        self.queue.push(ClickEvent(short_code, now_iso(), referrer, user_agent, ip, None))
        return long_url

    def get_stats(self, short_code):
        url_row = self.db.query_one("SELECT long_url FROM urls WHERE short_code = ?", (short_code,))
        if url_row is None:
            return None
        stats_row = self.db.query_one(
            "SELECT total_clicks, last_click_at FROM url_stats WHERE short_code = ?", (short_code,)
        )
        events = self.db.query(
            "SELECT ts, referrer, user_agent, ip FROM click_events WHERE short_code = ? ORDER BY ts DESC LIMIT 20",
            (short_code,),
        )
        return {
            "short_code": short_code,
            "long_url": url_row["long_url"],
            "total_clicks": stats_row["total_clicks"] if stats_row else 0,
            "last_click_at": stats_row["last_click_at"] if stats_row else None,
            "recent_events": [
                {"ts": e["ts"], "referrer": e["referrer"], "user_agent": e["user_agent"], "ip": e["ip"]}
                for e in events
            ],
        }

    def _get_row(self, short_code):
        return self.db.query_one("SELECT owner_key FROM urls WHERE short_code = ?", (short_code,))

    def update_url(self, short_code, owner_key, long_url=None, expires_at=None):
        row = self._get_row(short_code)
        if row is None:
            raise NotFoundError("short code not found")
        if row["owner_key"] and row["owner_key"] != owner_key:
            raise PermissionDeniedError("not the owner of this url")
        if long_url is not None:
            validate_url(long_url)
            self.db.execute("UPDATE urls SET long_url = ? WHERE short_code = ?", (long_url, short_code))
        if expires_at is not None:
            self.db.execute("UPDATE urls SET expires_at = ? WHERE short_code = ?", (expires_at, short_code))
        self.cache.invalidate(short_code)
        updated_row = self.db.query_one("SELECT long_url, expires_at FROM urls WHERE short_code = ?", (short_code,))
        return {
            "short_code": short_code,
            "long_url": updated_row["long_url"],
            "expires_at": updated_row["expires_at"],
            "updated": True,
        }

    def delete_url(self, short_code, owner_key):
        row = self._get_row(short_code)
        if row is None:
            raise NotFoundError("short code not found")
        if row["owner_key"] and row["owner_key"] != owner_key:
            raise PermissionDeniedError("not the owner of this url")
        self.db.execute("UPDATE urls SET active = 0 WHERE short_code = ?", (short_code,))
        self.cache.invalidate(short_code)
        return {"short_code": short_code, "deleted": True}
